### ISSUE TITLE
Unbound local true? Feel free to move & edit post

### ISSUE THREAD

**Issue by LeightonSmallshire** [slacka/WoeUSB#211] opened 2018-09-16 16:56 UTC
Installation failed!
Exit code: 256
Log:
WoeUSB v@@WOEUSB_VERSION@@
==============================
Mounting source filesystem...
Wiping all existing partition table and filesystem signatures in /dev/sdb...
/dev/sdb: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
/dev/sdb: calling ioctl to re-read partition table: Success
Ensure that /dev/sdb is really wiped...
Creating new partition table on /dev/sdb...
Creating target partition...
Making system realize that partition table has changed...
Wait 3 seconds for block device nodes to populate...
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
mkfs.fat 4.1 (2017-01-24)
Mounting target filesystem...
Applying workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
/usr/bin/woeusb: line 1348: true: unbound variable
Resetting workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
Unmounting and removing "/media/woeusb_source_1537116872_20564"...
Unmounting and removing "/media/woeusb_target_1537116872_20564"...
You may now safely detach the target device

**Comment by Lin-Buo-Ren** [comment] 2018-09-16 18:34
Duplicate of #207

**Closed by Lin-Buo-Ren** 2018-09-16 18:34 UTC
Labels: defect, duplicate
