### ISSUE TITLE
A important tip about error code:256

### ISSUE THREAD

**Issue by P9J7** [slacka/WoeUSB#158] opened 2018-01-22 08:28 UTC
I suggest use **shell** rather than gui, and add 
` --target-filesystem NTFS` is necessary when your iso's size bigger than 4Gib！Thanks another [issue](https://github.com/slacka/WoeUSB/issues/144) helps me realize this！:grinning:

**Comment by Lin-Buo-Ren** [comment] 2018-01-23 04:48
The 4GiB limitation is documented in this wiki article:  
https://github.com/slacka/WoeUSB/wiki/Limitations#fat32-filesystem-4gib-single-file-size-limitation

As this issue is essentially a duplicate of #144 it will be closed.

**Closed by Lin-Buo-Ren** 2018-01-23 04:48 UTC
