### ISSUE TITLE
/usr/bin/woeusb: line 1676: echo: write error: Invalid argument

### ISSUE THREAD

**Issue by alessandrorubio** [slacka/WoeUSB#272] opened 2019-07-18 19:33 UTC
I'm having [this](https://imgur.com/uUrEmc9) error.

I thought it was related to #271 and I tried to use woeusb on the terminal. Unfortunately, I got the [same error](https://imgur.com/4WfNb2m).

I'm using Manjaro **18.0.4** and woeusb **3.3.0-1** as stated [here](https://aur.archlinux.org/packages/woeusb)

**Comment by alessandrorubio** [comment] 2019-07-20 15:07
It seems that the issue is related to Woeusb on Manjaro. I did the same process on a Ubuntu machine and didn't get the error.

**Comment by Lin-Buo-Ren** [comment] 2019-07-20 18:20
Duplicate of #267.

**Closed by Lin-Buo-Ren** 2019-07-20 18:20 UTC

**Comment by michelfritsch** [comment] 2019-09-01 04:00
This error just occurs with me in kernel 5.2 in kernel 4.9 is ok.

**Comment by JpMaxMan** [comment] 2019-09-06 00:50
I actually upgraded to 5.2 from 4.19 and I get this error on both.

**Comment by Billy10mm** [comment] 2019-09-12 02:55
Getting this as well on 4.15.0-62-generic

**Comment by paulgault** [comment] 2019-10-12 19:14
getting this 4.4.0-165-generic, Ubuntu 16.04.6

**Comment by SylveonBottle** [comment] 2019-10-15 23:47
Getting this as well. uname -a `Linux pop-os 5.0.0-31-generic #33-Ubuntu SMP Mon Sep 30 18:51:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by aniljava** [comment] 2019-10-18 03:56
`Linux leela 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/root/Downloads :: # lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
`

Getting same error. But USB seems to be created just fine.

**Comment by lalten** [comment] 2019-10-20 13:27
I have the same error with woeusb `3.3.0-1~webupd8~bionic0`

uname -a:
```
Linux tpxy 5.1.15-050115-generic #201906250430 SMP Tue Jun 25 04:33:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

<details>
  <summary>Full Warning/Log:</summary>

```
Installation failed!
Exit code: 256
Log:
WoeUSB v@@WOEUSB_VERSION@@
==============================
Mounting source filesystem...
Wiping all existing partition table and filesystem signatures in /dev/sda...
/dev/sda: 5 bytes were erased at offset 0x00008001 (iso9660): 43 44 30 30 31
/dev/sda: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
/dev/sda: 8 bytes were erased at offset 0x00000200 (gpt): 45 46 49 20 50 41 52 54
/dev/sda: calling ioctl to re-read partition table: Success
Ensure that /dev/sda is really wiped...
Creating new partition table on /dev/sda...
Creating target partition...
Making system realize that partition table has changed...
Wait 3 seconds for block device nodes to populate...
Cluster size has been automatically set to 4096 bytes.
Creating NTFS volume structures.
mkntfs completed successfully. Have a nice day.
--2019-10-20 14:50:09--  https://github.com/pbatard/rufus/raw/master/res/uefi/uefi-ntfs.img
Resolving github.com (github.com)... 140.82.118.4
Connecting to github.com (github.com)|140.82.118.4|:443... pulse
connected.
HTTP request sent, awaiting response... pulse
302 Found
Location: https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/uefi-ntfs.img [following]
--2019-10-20 14:50:10--  https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/uefi-ntfs.img
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... pulse
151.101.192.133, 151.101.128.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... pulse
200 OK
Length: 524288 (512K) [application/octet-stream]
Saving to: ‘/tmp/WoeUSB.HBG8EH.tempdir/uefi-ntfs.img’
     0K .......pulse
... .......... .......... .......... ..........  9% 1,22M 0s
    50K .......... .......... .........pulse
. .......... .......... 19% 2,43M 0s
   100K .......... .......... .......... .......... .......... 29% 4,71M 0s
   150K .......... .......... .......... .......... .......... 39% 7,50M 0s
   200K .......... .......... .......... .......... .......... 48% 5,66M 0s
   250K .......... .......... .......... .......... .......... 58% 30,3M 0s
   300K .......... .......... .......... .......... .......... 68% 3,93M 0s
   350K .......... .......... .......... .......... .......... 78% 33,8M 0s
   400K .......... .......... .......... .......... .......... 87% 24,5M 0s
   450K .......... .......... .......... .......... .......... 97% 46,9M 0s
   500K .......... ..                                         100% 44,8M=0,1s
2019-10-20 14:50:10 (4,79 MB/s) - ‘/tmp/WoeUSB.HBG8EH.tempdir/uefi-ntfs.img’ saved [524288/524288]
1024+0 records in
1024+0 records out
524288 bytes (524 kB, 512 KiB) copied, 0,0760415 s, 6,9 MB/s
Mounting target filesystem...
Applying workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
Copying files from source media...
Installing GRUB bootloader for legacy PC booting support...
Installing for i386-pc platform.
Installation finished. No error reported.
Installing custom GRUB config for legacy PC booting...
Resetting workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
/usr/bin/woeusb: line 1676: echo: write error: Invalid argument
The command "exit 0" failed with exit status "1", program is prematurely aborted
```
</details>

**Comment by deniseiras** [comment] 2019-10-22 21:33
The error invalid argument, in my woeusb version (woeusb/xenial,now 3.3.0-1~webupd8~xenial0 amd64) is related when echoing to the files below, what is no possible (even using sudo):
echo "${VM_DIRTY_BACKGROUND_BYTES}" > /proc/sys/vm/dirty_background_bytes
echo "${VM_DIRTY_BYTES}" > /proc/sys/vm/dirty_bytes

So, I've just commented this lines, and didn't get the related error - workaround_linux_make_writeback_buffering_not_suck:

## Currently WoeUSB indirectly causes severely unresponsive system on 64-bit architecture with large primary memory during file copy process due to a flaw of the writeback buffer size handling in Linux kernel, workaround it before it is fixed
 related to an possible

**Comment by Kevin-2-Romero** [comment] 2019-10-28 03:32
> The error invalid argument, in my woeusb version (woeusb/xenial,now 3.3.0-1~webupd8~xenial0 amd64) is related when echoing to the files below, what is no possible (even using sudo):
> echo "${VM_DIRTY_BACKGROUND_BYTES}" > /proc/sys/vm/dirty_background_bytes
> echo "${VM_DIRTY_BYTES}" > /proc/sys/vm/dirty_bytes
> 
> So, I've just commented this lines, and didn't get the related error - workaround_linux_make_writeback_buffering_not_suck:
> 
> Currently WoeUSB indirectly causes severely unresponsive system on 64-bit architecture with large primary memory during file copy process due to a flaw of the writeback buffer size handling in Linux kernel, workaround it before it is fixed
> related to an possible

What file did you comment it out on? I have the same issue

**Comment by feanorknd** [comment] 2019-10-28 12:55
Note this:

> root@WBS-gino:/home/gino# echo 0 > /proc/sys/vm/dirty_background_bytes
> bash: echo: error de escritura: Argumento inválido
> root@WBS-gino:/home/gino# echo "0" > /proc/sys/vm/dirty_background_bytes
> bash: echo: error de escritura: Argumento inválido

So modify by using:

> nano +1676 /usr/bin/woeusb

Comment those lines:

> #echo 0 > /proc/sys/vm/dirty_background_bytes
> #echo 0 > /proc/sys/vm/dirty_bytes

I am currenty testing..

**Comment by diegogiglio** [comment] 2019-11-07 00:44
> Note this:
> 
> > root@WBS-gino:/home/gino# echo 0 > /proc/sys/vm/dirty_background_bytes
> > bash: echo: error de escritura: Argumento inválido
> > root@WBS-gino:/home/gino# echo "0" > /proc/sys/vm/dirty_background_bytes
> > bash: echo: error de escritura: Argumento inválido
> 
> So modify by using:
> 
> > nano +1676 /usr/bin/woeusb
> 
> Comment those lines:
> 
> > #echo 0 > /proc/sys/vm/dirty_background_bytes
> > #echo 0 > /proc/sys/vm/dirty_bytes
> 
> I am currenty testing..

it works perfectly to me
thank you a lot :)

**Comment by przemyslaw-szustak** [comment] 2019-11-13 16:06
I had this same problem at the moment.
Just run woeusb from root user not with sudo because you can't echo witch sudo.

**Comment by jjaaccoobb** [comment] 2019-11-14 20:25
`Linux leetbox 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

Experiencing the same...

**Comment by RickardBremer** [comment] 2019-11-19 17:53
/usr/bin/woeusb: line 1676: echo: write error: Invalid argument
The command "exit 0" failed with exit status "1", program is prematurely aborted

Linux nuc 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Cytomax55** [comment] 2019-11-21 02:26
Running Kubuntu 18.04.3 and i am running into the same error

**Comment by Boldie** [comment] 2019-11-24 19:16
xubunt 18.04.3 suffers from the same error: 5.0.0-36-generic

**Comment by baranowb** [comment] 2019-12-02 19:58
Linux drone-1-1 5.0.0-36-generic #39-Ubuntu SMP Tue Nov 12 09:46:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco

Present as well. Workaround seem to work.

**Comment by Cytomax55** [comment] 2019-12-02 21:15
It appears this topic is closed but people keep on adding to it.. you should repost here
https://github.com/slacka/WoeUSB/issues/267

**Comment by cleberson1** [comment] 2019-12-10 01:36
> Note this:
> 
> > root@WBS-gino:/home/gino# echo 0 > /proc/sys/vm/dirty_background_bytes
> > bash: echo: error de escritura: Argumento inválido
> > root@WBS-gino:/home/gino# echo "0" > /proc/sys/vm/dirty_background_bytes
> > bash: echo: error de escritura: Argumento inválido
> 
> So modify by using:
> 
> > nano +1676 /usr/bin/woeusb
> 
> Comment those lines:
> 
> > #echo 0 > /proc/sys/vm/dirty_background_bytes
> > #echo 0 > /proc/sys/vm/dirty_bytes
> 
> I am currenty testing..

Thanks man, my app was worked now

**Comment by MartinWeise** [comment] 2020-01-23 22:31
> Note this:
> 
> > root@WBS-gino:/home/gino# echo 0 > /proc/sys/vm/dirty_background_bytes
> > bash: echo: error de escritura: Argumento inválido
> > root@WBS-gino:/home/gino# echo "0" > /proc/sys/vm/dirty_background_bytes
> > bash: echo: error de escritura: Argumento inválido
> 
> So modify by using:
> 
> > nano +1676 /usr/bin/woeusb
> 
> Comment those lines:
> 
> > #echo 0 > /proc/sys/vm/dirty_background_bytes
> > #echo 0 > /proc/sys/vm/dirty_bytes
> 
> I am currenty testing..

Thank you very much! It works also on Ubuntu 19.10

**Comment by rgaufman** [comment] 2020-02-02 14:26
Any permanent solution? - getting the same on Ubuntu 18.04, using the workaround of commenting those lines out

**Comment by ZVNexus** [comment] 2020-02-12 15:53
> Any permanent solution? - getting the same on Ubuntu 18.04, using the workaround of commenting those lines out

New release came out. Ask the maintainer of the package for Ubuntu to update, I already updated Solus and the issue is fixed.

**Comment by grgbnc** [comment] 2020-10-09 18:38
1. done full system upgrade of Arch Linux (which installs WoeUSB v3.3.1)

2. after which, `uname -a` returns:

   ```
   Linux satellite-a500 5.8.14-arch1-1 #1 SMP PREEMPT Wed, 07 Oct 2020 23:59:46 +0000 x86_64 
   GNU/Linux
   ```

3. I invoke (as root):

   ```
   # woeusb --device Win10_2004_EnglishInternational_x64.iso /dev/sdc --target-filesystem NTFS
   ```

4. which, after correct execution of `wget` and `dd`, outputs:

   ```
   Mounting target filesystem...
   Applying workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
   Copying files from source media...
   Installing GRUB bootloader for legacy PC booting support...
   Installing for i386-pc platform.
   Installation finished. No error reported.
   Installing custom GRUB config for legacy PC booting...
   Resetting workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
   /usr/bin/woeusb: line 1683: echo: write error: Invalid argument
   Warning!: command "echo 0 > /proc/sys/vm/dirty_background_bytes" - returned code  $?
   /usr/bin/woeusb: line 1684: echo: write error: Invalid argument
   Warning: command "echo 0 > /proc/sys/vm/dirty_bytes" - returned code  $?
   Unmounting and removing "/media/woeusb_source_1602265495_9779"...
   Unmounting and removing "/media/woeusb_target_1602265495_9779"...
   You may now safely detach the target device
   Done :)
   The target device should be bootable now
   ```

Before the upgrade, I suffered from https://github.com/slacka/WoeUSB/issues/251

I will try the woe boot later, fingers crossed...
