### ISSUE TITLE
make compatible with dosfstools 4

### ISSUE THREAD

**Issue by schiffsratte** [slacka/WoeUSB#106] opened 2017-06-13 12:50 UTC
dosfstools seems to change in version 4 . mkdosfs is only a symlink to mkfs.fat, but the symlinks are not made in every case. (like on gentoo without compat use flag)
WoeUsb should check for mkfs.fat to check for dosfstools as a check for mkdosfs can fail, even if dosfstools are installed  on a system.

The dosfstools github page says: 
_The ./configure script has an option --enable-compat-symlinks that will configure the build to symlink older names of the tools to the current ones on installation. These are dosfsck, fsck.msdos and fsck.vfat for fsck.fat, mkdosfs, mkfs.msdos and mkfs.vfat for mkfs.fat and dosfslabel for fatlabel_

**Comment by Lin-Buo-Ren** [comment] 2017-06-13 13:04
Hello in fact WoeUSB detects both `mkfs.fat` and `mkdosfs`, however due to a regression you just found(congrats!) `mkfs.fat` is not properly detected and used

Should be fixed in the next release, thanks for reporting!

**Comment by Lin-Buo-Ren** [comment] 2017-06-13 13:25
Thanks for reporting the issue, this should be fixed in WoeUSB v2.0.10, please comment if you still have problem using that version

**Closed** 2017-06-13 13:24 UTC

**Comment by schiffsratte** [comment] 2017-06-13 13:35
Ok I'll try WoeUSB v2.0.10. Thank you

**Comment by schiffsratte** [comment] 2017-06-13 14:26
Issue has been fixed in 9cae433 ! Using dosfstools 4.0-r1 without -enable-compat-symlinks 
Thanks !
