### ISSUE TITLE
WoeUSB Error

### ISSUE THREAD

**Issue by eltonfabricio10** [slacka/WoeUSB#302] opened 2020-02-03 01:41 UTC
/usr/bin/woeusb: linha 1676: echo: erro de escrita: Argumento inválido        
The command "exit 0" failed with exit status "1", program is prematurely aborted

**Comment by XDfield** [comment] 2020-02-03 15:08
same here
os: ubuntu 18.04
iso: cn_windows_10_consumer_editions_version_1909_x64_dvd_76365bf8.iso

```bash
Installing GRUB bootloader for legacy PC booting support...
Installing for i386-pc platform.
Installation finished. No error reported.
Installing custom GRUB config for legacy PC booting...
Resetting workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
/usr/bin/woeusb: 第 1676 行: echo: 写错误: 无效的参数
The command "exit 0" failed with exit status "1", program is prematurely aborted
```

**Comment by dwilmer** [comment] 2020-02-11 16:51
Same here, adding full output in case it helps:

```
Installation failed!
Exit code: 256
Log:
WoeUSB v@@WOEUSB_VERSION@@
==============================
Mounting source filesystem...
Wiping all existing partition table and filesystem signatures in /dev/sda...
/dev/sda: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
/dev/sda: calling ioctl to re-read partition table: Success
Ensure that /dev/sda is really wiped...
Creating new partition table on /dev/sda...
Creating target partition...
Making system realize that partition table has changed...
Wait 3 seconds for block device nodes to populate...
Cluster size has been automatically set to 4096 bytes.
Creating NTFS volume structures.
mkntfs completed successfully. Have a nice day.
--2020-02-11 16:40:03--  https://github.com/pbatard/rufus/raw/master/res/uefi/uefi-ntfs.img
Resolving github.com (github.com)... 140.82.118.3
Connecting to github.com (github.com)|140.82.118.3|:443... connected.
HTTP request sent, awaiting response... pulse
302 Found
Location: https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/uefi-ntfs.img [following]
--2020-02-11 16:40:03--  https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/uefi-ntfs.img
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... pulse
200 OK
Length: 524288 (512K) [application/octet-stream]
Saving to: ‘/tmp/WoeUSB.RxZCcO.tempdir/uefi-ntfs.img’
     0K .......... .......... .......... .......... ..........  9% 5,35M 0s
    50K .......... .......... .......... .......... .......... 19% 6,63M 0s
   100K .......... .......... .......pulse
... .......... .......... 29% 10,7M 0s
   150K .......... .......... .......... .......... .......... 39% 8,25M 0s
   200K .......... .......... .......... .......... .......... 48% 12,1M 0s
   250K .......... .......... .......... .......... .......... 58% 11,1M 0s
   300K .......... .......... .......... .......... .......... 68% 9,57M 0s
   350K .......... .......... .......... .......... .......... 78% 7,36M 0s
   400K .......... .......... .......... .......... .......... 87% 10,6M 0s
   450K .......... .......... .......... .......... .......... 97% 13,2M 0s
   500K .......... ..                                         100%  123M=0,06s
2020-02-11 16:40:03 (9,01 MB/s) - ‘/tmp/WoeUSB.RxZCcO.tempdir/uefi-ntfs.img’ saved [524288/524288]
1024+0 records in
1024+0 records out
524288 bytes (524 kB, 512 KiB) copied, 0,116411 s, 4,5 MB/s
Mounting target filesystem...
Applying workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
Copying files from source media...
Installing GRUB bootloader for legacy PC booting support...
Installing for i386-pc platform.
Installation finished. No error reported.
Installing custom GRUB config for legacy PC booting...
Resetting workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
/usr/bin/woeusb: line 1676: echo: write error: Invalid argument
The command "exit 0" failed with exit status "1", program is prematurely aborted
```

**Comment by cheeesy** [comment] 2020-02-15 12:02
I'm having the same problem.

```Installing GRUB bootloader for legacy PC booting support...
i386-pc wird für Ihre Plattform installiert.
installation beendet. Keine Fehler aufgetreten.
Installing custom GRUB config for legacy PC booting...
Resetting workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
/usr/bin/woeusb: Zeile 1676: echo: Schreibfehler: Das Argument ist ungültig.
The command "exit 0" failed with exit status "1", program is prematurely aborted```

**Comment by dwilmer** [comment] 2020-02-15 18:44
Looking further, this seems to be a duplicate of #272

**Closed** 2021-12-01 01:13 UTC
