### ISSUE TITLE
line 2163 woeusb : RUNTIME_EXECUTABLE_NAME: unbound variable

### ISSUE THREAD

**Issue by decentris** [slacka/WoeUSB#234] opened 2018-12-26 02:55 UTC
## Issue Reproduce Instructions
> 1. Launch WoeUSB by running `woeusb`

## Expected Behavior
> No error

## Current Behavior
> WoeUSB errors with message "/bin/woeusb: line 2163: RUNTIME_EXECUTABLE_NAME: unbound variable"

## Info of My Environment
WoeUSB Version 3.2.12

### Information about the Operating System
> Centos 7

### Information about the Source Media
> "Windows 7 Professional Edition"

### Information about the Target Device
> "KingstonDataTraveler  - 8GB"

**Comment by Lin-Buo-Ren** [comment] 2018-12-26 04:18
Please elaborate how you install and execute the command in detail.

**Comment by decentris** [comment] 2018-12-26 10:17
Hi Lin,

sorry, completely forgot about that:

The bash --version shows:
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
License GPLv3+

I install woeUSB out of the following repository: 
https://centos.pkgs.org/7/nux-dextop-x86_64/WoeUSB-3.2.10-1.el7.nux.x86_64.rpm.html

All dependencies are also successfully installed (otherwise I wouldn't be able to install the woeUSB-RPM).

The error occurs:
When I open the GUI-Interface (which works like a charm), select the WIN-Install-ISO, select the according USB-Stick Device and click on "Intall" there is a pop-up window showing the following error message:

Installation failed!
Exit code: 256
Log:
/usr/bin/woeusb: line 2128:
RUNTIME_EXECUTABLE_NAME: unbound variable

Hope this helps. I'll be available for any further questions.

**Comment by fidencio** [comment] 2019-01-05 23:41
Okay, WoeUSB requires bash >= 4.3 in order to run while CentOS7 has GNU bash, version 4.2.46(2)-release.

I'm not sure why WoeUSB requires 4.3, but I'm kind of skeptical that a workaround could be found (unless you're able to build a new enough version of bash by yourself).

**Comment by Lin-Buo-Ren** [comment] 2019-01-06 03:13
@fidencio Thanks for verifying, as building a "new enough version of bash" is relatively easier than making WoeUSB compatible with Bash 4.2, closing as wont-fix.

REF: https://github.com/slacka/WoeUSB/wiki/Compatibility#gnu-bash

For making WoeUSB bail out when an incompatible bash version is found, refer issue #169

**Closed by Lin-Buo-Ren** 2019-01-06 03:13 UTC
Labels: defect

**Comment by feraligatr** [comment] 2019-03-27 16:16
I don't think it is caused by bash version. I've tested with bash 4.3 and 4.4. Both have the same issue as OP.

**Comment by Lin-Buo-Ren** [comment] 2019-07-02 02:12
Hello, apologies for not responding to this issue, however after a review a concluded that the current logic is proper(excluding from compatibility problems from old release):

* The expression `test -v 'BASH_SOURCE[0]'` should return true whenever the script isn't piped to bash (i.e. cat _script_ | bash), which shouldn't be the case for WoeUSB.
* The parameter RUNTIME_EXECUTABLE_NAME should be set regardless of it's value, thus shouldn't trigger the nounset failure condition

Please reply if you're still reproducing this issue, and this time, run the script with `bash -o xtrace woeusb`, thank you.

**Comment by bhmayor** [comment] 2019-10-17 16:32
To whom it shall concern:

$ bash -o xtrace woeusb
+ set -o errexit -o errtrace -o nounset -o pipefail
+ shopt -s expand_aliases
+ for critical_command in realpath basename dirname mktemp
+ command -v realpath
+ for critical_command in realpath basename dirname mktemp
+ command -v basename
+ for critical_command in realpath basename dirname mktemp
+ command -v dirname
+ for critical_command in realpath basename dirname mktemp
+ command -v mktemp
+ '[' -v 'BASH_SOURCE[0]' ']'
+ RUNTIME_COMMANDLINE_PARAMETERS=("${@}")
+ declare -ar RUNTIME_COMMANDLINE_PARAMETERS
+ declare global_only_for_gui=false
+ declare verbose=false
+ declare no_color=false
+ declare -ir 'DD_BLOCK_SIZE=((4 * 1024 * 1024))'
+ declare source_fs_mountpoint target_fs_mountpoint target_device
+ declare -i pulse_current_pid=0
+ declare current_state=pre-init
+ ENUM_SUPPORTED_FILESYSTEMS=([FS_FAT]='File Allocation Table(FAT)' [FS_NTFS]='New Technology File System(NTFS)')
+ declare -A ENUM_SUPPORTED_FILESYSTEMS
+ alias echo_with_color=util_echo_with_color switch_terminal_text_color=util_switch_terminal_text_color shift_array=util_shift_array is_target_busy=check_is_target_device_busy printf_with_color=util_printf_with_color
+ declare temp_directory
++ mktemp -d -t WoeUSB.XXXXXX.tempdir
+ temp_directory=/tmp/WoeUSB.9OJwtE.tempdir
+ declare -r temp_directory
+ declare -fr init
+ declare -fr print_help
+ declare -fr print_version
+ declare -fr print_application_info
+ declare -fr process_commandline_parameters
+ declare -fr process_miscellaneous_requests
+ declare -fr check_runtime_dependencies
+ declare -fr check_permission
+ declare -fr check_runtime_parameters
+ declare -fr determine_target_parameters
+ declare -fr check_is_target_device_busy
+ declare -fr check_source_and_target_not_busy
+ declare -fr wipe_existing_partition_table_and_filesystem_signatures
+ declare -fr check_if_the_drive_is_really_wiped
+ declare -fr create_target_partition_table
+ declare -fr workaround_make_system_realize_partition_table_changed
+ declare -fr create_target_partition
+ declare -fr create_uefi_ntfs_support_partition
+ declare -fr install_uefi_ntfs_support_partition
+ declare -fr workaround_buggy_motherboards_that_ignore_disks_without_boot_flag_toggled
+ declare -fr check_fat32_filesize_limitation
+ declare -fr check_target_partition
+ declare -fr check_uefi_ntfs_support_partition
+ declare -fr mount_source_filesystem
+ declare -fr mount_target_filesystem
+ declare -fr check_target_filesystem_free_space
+ declare -fr copy_filesystem_files
+ declare -fr copy_large_file
+ declare -fr workaround_support_windows_7_uefi_boot
+ declare -fr workaround_linux_make_writeback_buffering_not_suck
+ declare -fr install_legacy_pc_bootloader_grub
+ declare -fr install_legacy_pc_bootloader_grub_config
+ declare -fr cleanup_mountpoint
+ declare -fr trigger_wxGenericProgressDialog_pulse
+ declare -fr trap_errexit
+ declare -fr trap_exit
+ declare -fr trap_interrupt
+ declare -fr trap_return
+ declare -fr trap_debug
+ declare -fr util_call_external_command
+ declare -fr util_switch_terminal_text_color
+ declare -fr util_echo_with_color
+ declare -fr util_printf_with_color
+ declare -fr util_shift_array
+ declare -fr util_is_parameter_set_and_not_empty
+ declare -fr util_check_function_parameters_quantity
+ trap trap_exit EXIT
+ trap trap_errexit ERR
+ trap trap_interrupt INT
/usr/bin/woeusb: line 2128: RUNTIME_EXECUTABLE_NAME: unbound variable
++ trap_exit
++ local flag_unclean=false
++ local flag_unsafe=false
++ trigger_wxGenericProgressDialog_pulse off false
++ util_check_function_parameters_quantity 2 2
++ '[' 2 -ne 2 ']'
++ local -i expected_parameter_quantity=2
++ shift
++ local -i given_parameter_quantity=2
++ '[' 2 -ne 2 ']'
++ return 0
++ local switch=off
++ shift
++ local -r only_for_gui=false
++ '[' false = false ']'
++ return 0
++ case "${current_state}" in
++ util_is_parameter_set_and_not_empty source_fs_mountpoint
++ util_check_function_parameters_quantity 1 1
++ '[' 2 -ne 2 ']'
++ local -i expected_parameter_quantity=1
++ shift
++ local -i given_parameter_quantity=1
++ '[' 1 -ne 1 ']'
++ return 0
++ local parameter_name=source_fs_mountpoint
++ '[' '!' -v source_fs_mountpoint ']'
++ return 1
++ util_is_parameter_set_and_not_empty target_fs_mountpoint
++ util_check_function_parameters_quantity 1 1
++ '[' 2 -ne 2 ']'
++ local -i expected_parameter_quantity=1
++ shift
++ local -i given_parameter_quantity=1
++ '[' 1 -ne 1 ']'
++ return 0
++ local parameter_name=target_fs_mountpoint
++ '[' '!' -v target_fs_mountpoint ']'
++ return 1
++ '[' false = true ']'
++ '[' false = true ']'
++ unset flag_unclean flag_unsafe
++ util_is_parameter_set_and_not_empty target_device
++ util_check_function_parameters_quantity 1 1
++ '[' 2 -ne 2 ']'
++ local -i expected_parameter_quantity=1
++ shift
++ local -i given_parameter_quantity=1
++ '[' 1 -ne 1 ']'
++ return 0
++ local parameter_name=target_device
++ '[' '!' -v target_device ']'
++ return 1
++ rm --recursive /tmp/WoeUSB.9OJwtE.tempdir
++ '[' pre-init = finished ']'
++ return 0
 
$ cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)
 
$ sudo yum list installed | grep -i woeusb
WoeUSB.x86_64                           3.2.10-1.el7.nux               @nux-dextop

**Comment by felag** [comment] 2019-10-31 13:15
Hello there, I had exact same error and messages.
I believe you will also encounter errors on lines containing ``local -n`` and ``define -n`` internal bash commands.



I could workaround this issue using bash 5 on CentOS7 (See below for a quick howto).

- Step 1:
```
# wget http://ftp.gnu.org/gnu/bash/bash-5.0.tar.gz
[…]
# tar xvzf bash-5.0.tar.gz
[…]
# cd bash-5.0
# ./configure && make && make install
[…can be quite verbose here…]
# /usr/local/bin/bash --version
GNU bash, version 5.0.0(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

- Step 2:
Adding 2 lines at very top of ``/bin/woeusb`` file (make a backup copy before!!) :
```
#!/usr/local/bin/bash
## use bash v5
```

And you're done ! \o/ (The time I type this here WoeUSB is now at 15%…)

Hope this helps, please comment if you tested this (with or without success).

**Comment by rockocoop** [comment] 2020-03-17 16:19
@felag worked! Thanks!

**Comment by yoyo42** [comment] 2020-04-14 21:38
Confirm, installing bash v5 from source worked for me on CentOS 7.7.1908 too. Thanks!
