### ISSUE TITLE
Ubuntu 16.04 : Exit code 32512

### ISSUE THREAD

**Issue by martijnhiemstra** [slacka/WoeUSB#152] opened 2017-11-06 09:00 UTC
I am running Ubuntu 16.04 and when I start the application I get the following error:

Installation failed !
Exit code: 32512
Log:

This is when I am running the gui. I have not tried from the console.

**Comment by Lin-Buo-Ren** [comment] 2017-11-06 09:40
> Installation failed !

You are probably not using the latest release, please follow the instructions in https://github.com/slacka/WoeUSB (README) to build & install the latest development snapshot to see if the issue can still be reproduced.

Also this seems to be an duplicate of issue #136 , please discuss the matter it that issue.

**Closed by Lin-Buo-Ren** 2017-11-06 09:40 UTC
