### ISSUE TITLE
How to use Legacy boot？

### ISSUE THREAD

**Issue by Hello-Linux** [slacka/WoeUSB#310] opened 2020-03-12 22:39 UTC
My computer doesn't support UEFI boot. How can I make woeusb support Legacy boot? I downloaded a win7 image. After installation, my USB flash drive is UEFI. Why?

**Comment by JonnyTech** [comment] 2020-03-12 23:03
The flash drive created is dual boot - it will appear as both a legacy (BIOS) and UEFI device.

**Comment by Hello-Linux** [comment] 2020-03-12 23:07
@JonnyTech  Do you mean my USB drive supports Legacy boot?

**Comment by JonnyTech** [comment] 2020-03-12 23:27
Yes, when created from WoeUSB, in a legacy system the drive boots as MBR only, in a UEFI system the drive can appear as MBR/BIOS, GPT/UEFI or both depending on how you set up your system.

So if your computer is BIOS/legacy only then just make sure that you have set it to boot from a USB device, and try all ports because, from experience, on some older systems not all USB ports support booting.

**Comment by Hello-Linux** [comment] 2020-03-13 00:36
The launcher is finished. When I boot from usb, the computer directly jumps to the grub command interface, and the Anto operating system interface does not appear. Why is this?

**Comment by Lin-Buo-Ren** [comment] 2020-03-13 02:07
Check out
https://github.com/slacka/WoeUSB/wiki/F.A.Q.#my-usb-is-not-listed-in-the-boot-device-selection-menulegacy-pc-bootingcsm
for possible solution.

Hello-Linux <notifications@github.com> 於 2020年3月13日 週五 上午8:36 寫道：

**Comment by JonnyTech** [comment] 2020-03-13 05:19
> the computer directly jumps to the grub

The USB has booted correctly on your device

> the Anto operating system

What is "Anto"? This project is designed for making bootable **Windows** media.

Can you provide a link to the ISO file that you used?

**Comment by Hello-Linux** [comment] 2020-03-13 13:20
U disk boot directly to this interface
![webwxgetmsgimg](https://user-images.githubusercontent.com/17851645/76624526-6f85be80-6570-11ea-9ad1-052eca99cef7.jpg)

**Comment by JonnyTech** [comment] 2020-03-13 13:31
That looks like an unofficial build of Windows. We cannot guarantee that these will function correctly since whoever created this ISO may not have done it properly. Please test with an official Microsoft ISO.

**Comment by Hello-Linux** [comment] 2020-03-14 00:48
@JonnyTech  In China, we generally do not use the official mirror image.

**Comment by JonnyTech** [comment] 2020-03-15 14:04
What is the first partition in red? That should not be there. Can you provide a text output from something like `fdisk`. There should be only the other two partitions. Please wipe / zero the drive then run `woeusb` again.

Once you test with an official image then let me know the results. If the official image also has issues then we can investigate further.

**Comment by Lin-Buo-Ren** [comment] 2020-03-15 14:26
@JonnyTech 
> What is the first partition in red? That should not be there.

I assume that's just the theme colored of a selected UI.

**Comment by Lin-Buo-Ren** [comment] 2020-03-15 14:35
@Hello-Linux 

>  In China, we generally do not use the official mirror image.

I do acknowledge this fact, however we only support official Microsoft images due to limited resources, so unless the corresponding official image also can't boot there's not much we can help.  Feel free to send patches, though.

> the computer directly jumps to the grub command interface, and the Anto operating system interface does not appear. Why is this?

It's likely that [the boot script](https://github.com/slacka/WoeUSB/blob/f21bb19/src/woeusb#L1736-L1739) failed.

> I also want to know if I need to do other operations on my USB flash drive before installing the U boot disk?

If the disk preparation is successful it should be boot-able without modifications.

**Comment by JonnyTech** [comment] 2020-03-15 15:43
> I assume that's just the theme color of a selected UI.

@Lin-Buo-Ren: Indeed, but it does have a size of 4.2MB. The first partition should be there, not another partition or even free space. I am interested to know.

@Hello-Linux: Did you use the `--device` option in the command line?

**Comment by Lin-Buo-Ren** [comment] 2020-03-17 07:52
@JonnyTech Refer https://github.com/slacka/WoeUSB/blob/f21bb19/src/woeusb#L1075 for the info regarding the 4.0MiB free space at the start of the disk.

**Comment by JonnyTech** [comment] 2020-03-17 11:12
Good, thanks for confirming that it is free space, it was not clear whether is was used.

**Comment by myl7** [comment] 2021-01-22 13:01
I met the same situation as @Hello-Linux , and noticed `Disklabel type: dos` in fdisk info. After creating a new gpt partition table with `fdisk /dev/sdx` and `g`, I was able to boot into Windows.

**Comment by rootHNC** [comment] 2021-06-02 21:11
![Captura de pantalla_2021-06-02_23-10-40](https://user-images.githubusercontent.com/81411511/120552682-d272a800-c3f7-11eb-9e72-1b560d41fcb8.png)
ummm that dont work

**Comment by Lin-Buo-Ren** [comment] 2021-06-03 05:33
> ummm that dont work

If you mean the long time stall problem at the `Instalando para plataforma i386-pc` it is expected behavior due to the I/O limitation of your device.  Please use FAT filesystem as your target filesystem to avoid it.  Refer [Installation using NTFS takes too looooooong (was: Installing for i386-pc platform suffer) · Issue #18 · WoeUSB/WoeUSB](https://github.com/WoeUSB/WoeUSB/issues/18) for more info.

**Comment by Lin-Buo-Ren** [comment] 2021-06-03 05:38
> I met the same situation as @Hello-Linux , and noticed `Disklabel type: dos` in fdisk info. After creating a new gpt partition table with `fdisk /dev/sdx` and `g`, I was able to boot into Windows.

Apologies for the ignorance, the MBR partition scheme usage is expected as UEFI firmware should have no problem booting from them (contrary to what Microsoft Windows *limitation* of only supporting GUID Partition Table for Windows installation on UEFI firmware) and is not relevant to this issue.  If you still have difficulty on using WoeUSB please file a new issue on WoeUSB/WoeUSB, thank you.

**Comment by Lin-Buo-Ren** [comment] 2021-06-03 05:39
Closing the issue as not-our-scope.

**Closed by Lin-Buo-Ren** 2021-06-03 05:39 UTC
Labels: not-our-scope
