### ISSUE TITLE
Installation failed! Exit code: 32512 Log: /bin/sh: 1: woeusb: not found

### ISSUE THREAD

**Issue by e11i0t23** [slacka/WoeUSB#163] opened 2018-02-24 23:12 UTC
Installation failed!
Exit code: 32512
Log:
/bin/sh: 1: woeusb: not found

i am running on kali linux iso is for windows server 2016

**Comment by Lin-Buo-Ren** [comment] 2018-02-25 09:23
Probably a duplicate of #136, feel free to comment if it isn't.

**Closed by Lin-Buo-Ren** 2018-02-25 09:23 UTC
