### ISSUE TITLE
/usr/bin/woeusb: line 1683: echo: write error: Invalid argument

### ISSUE THREAD

**Issue by kopax** [slacka/WoeUSB#324] opened 2020-06-09 21:37 UTC
## Good Habit Checklist for Issue Reporting
Checkout [Mastering Markdown · GitHub Guides](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) if you need help on the GitHub-flavored Markdown syntax.  You may remove sections and contents that don't apply.

* [x] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed
* [x] I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

## Issue Reproduce Instructions

1. Launch WoeUSB by running `sudo woeusb --target-filesystem NTFS  --device /home/dka/Downloads/Win10_1909_French_x64.iso  /dev/sdc
`

## Expected Behavior
> No error

## Current Behavior

```
/usr/bin/woeusb: line 1683: echo: write error: Invalid argument
Warning!: command "echo 0 > /proc/sys/vm/dirty_background_bytes" - returned code  $?
/usr/bin/woeusb: line 1684: echo: write error: Invalid argument
```

### WoeUSB Version
> For source code build, run `git describe --tags --always --dirty` under the source tree, for prebuilt releases refer the source that provides WoeUSB

### WoeUSB Source
3.3.1

### GNU Bash Version
5.4
### Information about the Operating System
Debian stretch

### Information about the Source Media
> "Windows 10 french amd 64" downloaded from <https://microsoft.com/download/windows-10>

### Information about the Target Device

Data Traveler 64GB (USB 3.1 variant)

**Comment by fbuetler** [comment] 2020-10-23 20:35
Actually commenting (the line numbers differ because of some updates on the script)
```
1679             # echo 0 > /proc/sys/vm/dirty_background_bytes
1680             # echo 0 > /proc/sys/vm/dirty_bytes
```
solved it for me and it run throught without an error.  
Some research showed
```
/proc/sys/vm/dirty_background_bytes

Amount of total available memory (MemFree + Cached - Mapped) in which write operations can 
be cached before they are written back to disk by a background flusher process of the kernel.

dirty_background_bytes is the opposite of dirty_background_ratio. Only one of the two settings 
can be active. Setting one value automatically sets the other value to 0.

/proc/sys/vm/dirty_bytes

Amount of total available memory (MemFree + Cached - Mapped) in which write operations can 
be cached before the processes are forced to write the buffer to disk in the time allotted to them.

When this happens, all processes with write operations will be halted, not just the process that 
filled the buffer. This behavior can be unfair, as one process can block the entire IO of the system.

dirty_bytes is the opposite of dirty_ratio. Only one of the two settings can be active. Setting one 
value automatically sets the other value to 0.
```
I think the problem is that those files are no writables by the OS even with `sudo`

**Comment by seisdr** [comment] 2020-10-23 22:18
/dev/sda?

**Comment by fbuetler** [comment] 2020-10-23 23:19
> /dev/sda?

this is your device. see `lsblk` to look up your device

**Comment by seisdr** [comment] 2020-10-23 23:33
sda is my hard drive it's better not to copy and paste that I almost done it haha
anyway that solution didn't work same error

**Comment by seisdr** [comment] 2020-10-23 23:36
should I do write this command first ?
```
echo 0 > /proc/sys/vm/dirty_background_bytes
```
because I didn't

**Comment by seisdr** [comment] 2020-10-24 01:20
how can I make wine detect the usb

**Comment by seisdr** [comment] 2020-10-24 23:45
same result and damn it's so hard to echo zero to proc

**Comment by Lin-Buo-Ren** [comment] 2020-11-15 16:28
[WoeUSB 5.0.1](https://github.com/WoeUSB/WoeUSB/releases/tag/v5.0.1) drops the Linux kernel writes a buffering workaround which resolving this issue as a side affect.

**Closed by Lin-Buo-Ren** 2020-11-15 16:28 UTC
