### ISSUE TITLE
non-ASCII characters filename become garbled(mojibake) in target filesystem(orig. Wrong encoding for cyrillic symbols)

### ISSUE THREAD

**Issue by notuxius** [slacka/WoeUSB#135] opened 2017-08-16 09:08 UTC
If there are files/folders with cyrillic (russian) symbols inside iso file - there are wrongly encoded on target USB device.

### WoeUSB Version
2.1.0-5-g353d7db

### OS Distribution
Netrunner Rolling

### Source Media Info
"Windows 7 Ultimate Ru x86-x64 Orig wBootMenu by OVGorskiy 03.2017"

![wrong-encoding-cyrillic](https://user-images.githubusercontent.com/2657014/29356058-ad5e1f16-827b-11e7-8b7e-6b4229ea575c.png)

**Comment by Lin-Buo-Ren** [comment] 2017-08-16 09:15
This is probably due to the encoding/iocharset used in FAT filesystem, currently no easy way to determine what character set to be use as FAT filesystem mount options, the only feasible solution might be force using UTF-8(not sure if it's compatibility) or letting user to specify the proper mount parameter values.

**Comment by Lin-Buo-Ren** [comment] 2017-10-25 17:45
FAT filesystem *does* uses Unicode(UCS-2) in long filenames(LFN) so the issue doesn't seems to be in the FAT filesystem driver.  The cause might be in the source image's mounting option.

**Comment by Lin-Buo-Ren** [comment] 2017-10-25 19:18
I managed to fetch the exact source image and reproduced the issue, here's the found facts: 

* The filename is NOT mojibake from the source image, as can be seen during the copy process:
    > INFO: Copying "./Доп материал/Гаджеты рабочего стола/MeinWetter.gadget/img/msn/w2/13.png"...
* The filename IS mojibake when mounting the target filesystem again using Udisks, mount options: `rw,nosuid,nodev,relatime,uid=<caller-uid>,gid=<caller-gid>,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,showexec,utf8,flush,errors=remount-ro,uhelper=udisks2`
* The filename is NOT mojibake when mounting the target filesystem using `mount` as root (without  specifying any mounting options, which in turn uses `rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro`)

**Comment by Lin-Buo-Ren** [comment] 2017-10-26 06:04
The filename is also mojibake when mounted on codepage 950 Windows

![_359](https://user-images.githubusercontent.com/13408130/32019017-5a2a0bec-b9fe-11e7-87e5-ffc13ffb075c.png)

**Comment by Lin-Buo-Ren** [comment] 2017-10-26 16:57
This issue is due to the wrong mounting options of the target filesystem, it is fixed in commit b5291e.

**Closed by Lin-Buo-Ren** 2017-10-26 16:57 UTC
Labels: bug, help wanted

**Comment by luongdev** [comment] 2020-07-17 08:58
LOL
