### ISSUE TITLE
Error: Not enough free space on target partition!

### ISSUE THREAD

**Issue by netikras** [slacka/WoeUSB#125] opened 2017-07-22 08:58 UTC
`
netikras-xps ~ # lsblk /dev/sda
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    1  3,8G  0 disk 
└─sda1   8:1    1  3,8G  0 part 

netikras-xps ~ # woeusb --install /home/netikras/received/Win10_1607_Lithuanian_x64.iso /dev/sda1 
WARNING: The deprecated --install option is still available but will be dropped in WoeUSB v3.0!
Mounting source filesystem...
Error: Not enough free space on target partition!
Error: We required 3,7G(3975095413 bytes) but '/dev/sda1' only has 3,3G(3454513152 bytes).
Unmounting and removing '/media/woeusb_source_1500713634_12534'...
Unmounting and removing '/media/woeusb_target_1500713634_12534'...
You may now safely detach the target device

netikras-xps ~ # fdisk -l | grep /dev/sda
Disk /dev/sda: 3,8 GiB, 4037017600 bytes, 7884800 sectors
/dev/sda1        8192 7884799 7876608  3,8G  c W95 FAT32 (LBA)
netikras-xps ~ # 
`

Allright, HOW is that not enough space....? Where is that 3.3G from?

**Comment by netikras** [comment] 2017-07-22 09:01
`netikras-xps ~ # woeusb --device /home/netikras/received/Win10_1607_Lithuanian_x64.iso /dev/sda
Overwriting "/dev/sda"'s partition table...
Wait 3 seconds for block device nodes to populate...
mkfs.fat 3.0.28 (2015-05-16)
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
Mounting source filesystem...
Error: Not enough free space on target partition!
Error: We required 3,7G(3975095413 bytes) but '/dev/sda1' only has 3,3G(3504844800 bytes).
Unmounting and removing '/media/woeusb_source_1500714063_15965'...
Unmounting and removing '/media/woeusb_target_1500714063_15965'...
You may now safely detach the target device
netikras-xps ~ # 
`

**Comment by Lin-Buo-Ren** [comment] 2017-07-22 14:30
The code that does the check is [check_target_filesystem_free_space](https://github.com/slacka/WoeUSB/blob/master/src/woeusb#L719), we uses `df` and `du` to read the sizes.

**Comment by Lin-Buo-Ren** [comment] 2017-07-22 14:47
The problem might be your /dev/sda1 filesystem isn't empty and the *free* space(not the total) is not enough to fit the source image files.

Please check if /dev/sda1 has the required free space.

**Comment by Lin-Buo-Ren** [comment] 2017-07-22 15:28
```
netikras-xps ~ # woeusb --device /home/netikras/received/Win10_1607_Lithuanian_x64.iso /dev/sda
Overwriting "/dev/sda"'s partition table...
Wait 3 seconds for block device nodes to populate...
mkfs.fat 3.0.28 (2015-05-16)
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
Mounting source filesystem...
Error: Not enough free space on target partition!
Error: We required 3,7G(3975095413 bytes) but '/dev/sda1' only has 3,3G(3504844800 bytes).
```

The next output is more interesting as the `--device` mode is used while `woeusb` still complains about lack of free space.  Please wait until I figure out the instruction to investigate this issue, also you may want to checkout `src/woeusb` for any clues.

**Comment by JonnyTech** [comment] 2017-07-22 15:32
@netikras please provide the output from df /dev/sda1 and du /dev/sda1

**Comment by Lin-Buo-Ren** [comment] 2017-07-22 15:38
Please run `sudo parted <target-device> --script unit s print` paste the output of the command in terminal

Also please run `sudo lsblk --output NAME,MODEL,SIZE,MOUNTPOINT,FSTYPE,UUID` **before** and **after** running `sudo woeusb --device <source-image> <target-device>` and paste the output of each command in terminal

**Comment by netikras** [comment] 2017-07-22 19:54
what the f** was that..... My laptop simply turned off while I was running woeusb. it did not shut down. It powered off.

That's a first.....

I have a suspicion that I might have a faulty USB drive as woeusb seemed to be copying things into the drive this time. 18%+. Pure magic I guess.

I'll play arround with the drive a little more to see what happens next.

**Comment by netikras** [comment] 2017-07-22 19:54
netikras@netikras-xps ~ $ df -B1 -PT /media/netikras/Windows\ USB/
Failų sistema  Tipas    1-blokų       Naud     Laisva Capacity Prijungta prie
/dev/sda1      vfat  4024942592 1215291392 2809651200      31% /media/netikras/Windows USB
netikras@netikras-xps ~ $

**Comment by Lin-Buo-Ren** [comment] 2017-07-23 07:35
Hello, can this issue be reproduced?  If not I shall close it for now.

**Comment by Lin-Buo-Ren** [comment] 2017-08-01 07:38
Closing for not seems to be a bug in code.

**Closed by Lin-Buo-Ren** 2017-08-01 07:38 UTC
Labels: bug
